FROM alpine:3.16

RUN apk add --no-cache gcc musl-dev

COPY . /poker/

WORKDIR /poker/

RUN gcc main.c tests/tests.c game/game.c game/deck/deck.c menu/menu.c log/log.c

RUN ls | grep -xv "a.out" | xargs rm -r

ENTRYPOINT ./a.out