#define DATA_SIZE 1446
#define TARGET_SIZE 10
#define MINUTE_SIZE 9
#define TARGET_DEPTH 2
#define CSV_IN_LOCATION "./assets/FitbitData-1.csv"
#define CSV_OUT_LOCATION "./out/Results.csv"
#define FITBIT_ENTRY_POINT 3
#define RUN_TESTS 0
#define REQUIRED_COLUMNS 8
#define MAX_LINE_SIZE 40