FROM alpine:3.16

RUN apk add --no-cache gcc musl-dev

COPY . /battleship/

WORKDIR /battleship/

RUN gcc main.c board/board.c game/game.c game/player/battleship_player.c menu/menu.c messages/messages.c

RUN ls | grep -xv "a.out" | xargs rm -r

ENTRYPOINT ./a.out