#pragma once
#define POKER_HAND_AMOUNT 5

// can only be 5 players
#define POKER_PLAYER_AMOUNT 2

#define POKER_REPLACE_AMOUNT 3
#define POKER_DECK_AMOUNT 52
#define CARD_VALUE_AMOUNT 13
#define CARD_FACE_AMOUNT 4
#define POKER_STARTING_MONEY_AMOUNT 10000
#define POKER_SHUFFLE_AMOUNT 100

typedef enum {
    HIGH_CARD,
    PAIR,
    TWO_PAIR,
    THREE_OF_A_KIND,
    STRAIGHT,
    FLUSH,
    FULL_HOUSE,
    FOUR_OF_A_KIND,
    ROYAL_FLUSH
} PokerHand;