#define POKER_CARD_AMOUNT 5
#define POKER_PLAYER_AMOUNT 1
#define POKER_REPLACE_AMOUNT 3
#define POKER_DECK_AMOUNT 52
#define CARD_VALUE_AMOUNT 13
#define CARD_FACE_AMOUNT 4
#define POKER_STARTING_MONEY_AMOUNT 10000